<a href="https://colab.research.google.com/github/Arachne0/Mathematics_Basics/blob/master/Machine_Learning_for_math_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
c = np.array([2, 3])
d = np.array([1, 3])
c + d

array([3, 6])

In [ ]:
import numpy as np
x = np.matrix([[1, 0, 0],[0, 1, 0],[0, 0, 1]])
print(x)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
import numpy as np
list1 = [0, 1, 2, 3, 4, 5]
a = np.array(list1)

In [ ]:
print(a[list1])

[0 1 2 3 4 5]


In [ ]:
import numpy as np
a = np.array([[1., 2.], [3., 4.]])
np.linalg.inv(a)   # 역행렬

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
np.linalg.det(a)   # 행렬식

-2.0000000000000004

In [ ]:
# sklearn 패키지 decomposition 모듈의 PCA 함수 불러오기
from sklearn.decomposition import PCA
import numpy as np
M = np.array( [[-1, -1, -1], [-2, -1, 2], [-3, -2, 0], 
               [1, 1, 2], [2, 1, 1], [3, 2, 4], [2, 0, 3], 
               [3, 5, 1], [4, 2, 3], [3, 3, 2]] )   # 원래 데이터
               
pca = PCA(n_components=2)                       # 주성분을 두 개로 지정

In [ ]:
# 주성분 분석
pca.fit(M)
PCA(copy=True, iterated_power='auto', n_components=2, 
    random_state=None, svd_solver='auto', tol=0.0, whiten=False)
PC = pca.transform(M)

In [ ]:
# w는 고윳값, V는 고유 벡터
w, V = np.linalg.eig(pca.get_covariance())

In [ ]:
# 원래 데이터를 나타내는 주성분 세 개
V.T.dot(M.T).T

array([[-1.63789386,  0.38309423, -0.41296792],
       [-1.50265209, -1.67967793,  1.98008049],
       [-3.43143719, -0.83088857,  0.73134327],
       [ 1.9287851 , -0.84878936,  1.24873722],
       [ 2.3753258 ,  0.28259255,  0.52722744],
       [ 4.59500215, -1.03189193,  2.61173397],
       [ 2.3475376 , -0.06571181,  2.73582697],
       [ 5.55104049, -1.38406422, -1.5067567 ],
       [ 5.04154285,  0.09948998,  1.89022418],
       [ 4.62279035, -0.68358757,  0.40313444]])

In [ ]:
# numpy, scipy 이용해 다양한 선형대수 연산하기

import numpy as np
from scipy import linalg, sparse

# 다양한 행렬 생성하기
A = np.matrix(np.random.random((2, 2)))    # 임의의 2×2 행렬
b = np.random.random((2, 2))               # 2×2의 numpy array를 생성
B = np.asmatrix(b)                         # 2차원 배열을 행렬로 변환
C = np.mat(np.random.random((10, 5)))      # 임의의 10×5 행렬
D = np.mat([[3, 4], [5, 6]]) # 2차원 자료를 나타낸 리스트를 행렬로 표현


In [ ]:
# 생성된 행렬값을 출력하기(A, B, C는 랜덤하게 생성된 행렬이어서 출력되는 값은 다를 수 있음)
print(A)

[[0.78866299 0.72494365]
 [0.17213923 0.7319817 ]]


In [ ]:
print(B)

[[0.07062985 0.40602966]
 [0.74702347 0.43271061]]


In [ ]:
print(C)

[[0.9621314  0.63459917 0.99583155 0.50045625 0.05284605]
 [0.85679086 0.50327501 0.76147763 0.95799344 0.99400394]
 [0.9629099  0.35050678 0.49078216 0.11915499 0.01652615]
 [0.60750068 0.5393088  0.74016879 0.38195393 0.12619102]
 [0.81369394 0.8140144  0.6807488  0.12028237 0.42336735]
 [0.88361726 0.27408415 0.17229071 0.66637383 0.39087797]
 [0.20703917 0.38930394 0.98417336 0.73217738 0.08321891]
 [0.14265929 0.59915876 0.83533824 0.06149408 0.51168124]
 [0.97179285 0.59840005 0.04304494 0.21153104 0.80632324]
 [0.94851972 0.17780218 0.14521625 0.69791707 0.68315506]]


In [ ]:
print(D)

[[3 4]
 [5 6]]


In [ ]:
A.I                # A의 역행렬

matrix([[ 1.61765471, -1.60210087],
        [-0.38042185,  1.74291846]])

In [ ]:
linalg.det(A)      # A의 행렬식

0.4524956346818031

In [ ]:
A.T                # A의 전치행렬

matrix([[0.78866299, 0.17213923],
        [0.72494365, 0.7319817 ]])

In [ ]:
np.add(A, D)       # A와 D의 합


matrix([[3.78866299, 4.72494365],
        [5.17213923, 6.7319817 ]])

In [ ]:
np.subtract(A, D)  # A와 D의 차


matrix([[-2.21133701, -3.27505635],
        [-4.82786077, -5.2680183 ]])

In [ ]:
np.divide(A, D)    # A 나누기 D

matrix([[0.26288766, 0.18123591],
        [0.03442785, 0.12199695]])

In [ ]:
print(D@B)                   # D와 B의 행렬곱을 @로 계산


[[3.19998344 2.94893143]
 [4.83529009 4.62641198]]


In [ ]:
print(np.dot(D, B))          # D와 B의 행렬곱을 numpy의 dot 함수로도 게산할 수 있다

[[3.19998344 2.94893143]
 [4.83529009 4.62641198]]


In [ ]:
print(np.multiply(D, B))     # 행렬 D와 B에 대해서, 행렬곱이 아닌 대응되는 원소끼리의 단순 곱셈 수행
 

[[0.21188956 1.62411865]
 [3.73511736 2.59626366]]


In [ ]:
G = np.mat(np.identity(2))   # 2×2 항등행렬
G

matrix([[1., 0.],
        [0., 1.]])

In [ ]:
linalg.eigvals(A)       # 행렬 A의 고윳값 확인

array([1.11471539+0.j, 0.4059293 +0.j])

In [ ]:
la, v = linalg.eig(A)   # A의 고유 벡터

In [ ]:
l1, l2 = la             # 고윳값을 l1, l2로 받기
v[:,0]                  # 첫 번째 고유 벡터

array([0.91200258, 0.41018447])

In [ ]:
v[:,1]                  # 두 번째 고유 벡터

array([-0.88432203,  0.46687745])

In [ ]:
C[C > 0.5] = 0
H = sparse.csr_matrix(C)   # C를 희소행렬 형태로 변환
H.todense()                # H를 일반적인 행렬(dense matrix) 형태로 변환

matrix([[0.        , 0.        , 0.        , 0.        , 0.05284605],
        [0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.35050678, 0.49078216, 0.11915499, 0.01652615],
        [0.        , 0.        , 0.        , 0.38195393, 0.12619102],
        [0.        , 0.        , 0.        , 0.12028237, 0.42336735],
        [0.        , 0.27408415, 0.17229071, 0.        , 0.39087797],
        [0.20703917, 0.38930394, 0.        , 0.        , 0.08321891],
        [0.14265929, 0.        , 0.        , 0.06149408, 0.        ],
        [0.        , 0.        , 0.04304494, 0.21153104, 0.        ],
        [0.        , 0.17780218, 0.14521625, 0.        , 0.        ]])

In [ ]:
sparse.isspmatrix_csr(H)   # 희소행렬 여부 확인
True

True