<a href="https://colab.research.google.com/github/Arachne0/Mathematics_Basics/blob/master/machine_Learning_for_math_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
x = np.arange(10.0)            # 0~9까지 실수 10개를 갖는 자료 구조 생성
x.mean()   # x의 평균

4.5

In [ ]:
numbers=np.arange(20.0)        # 0~19까지 실수 20개로 1차원 배열 생성
x= np.reshape(numbers,(4,5))   # numbers를 4행 5열로 변경
np.mean(x,0)

array([ 7.5,  8.5,  9.5, 10.5, 11.5])

In [ ]:
np.std(x)    # 행과 열을 고려하지 않고 x에 대한 표준편차

5.766281297335398

In [ ]:
np.var(x)    # 행과 열 고려하지 않고 x에 대한 분산

33.25

In [ ]:
x= np.random.randn(3, 4)    # 3행 4열인 x
# x의 행별로 피어슨 상관관계 구하기, 예를 들어 1행과 2행의 상관관계, 2행과 3행의 상관관계 등. 결과는 3행 3열로 나오며, 랜덤하게 생성되어 결과는 다를 수 있음
np.corrcoef(x)

array([[ 1.        , -0.95926517,  0.41662392],
       [-0.95926517,  1.        , -0.53233559],
       [ 0.41662392, -0.53233559,  1.        ]])

In [ ]:
np.corrcoef(x[0],x[1])

array([[ 1.        , -0.95926517],
       [-0.95926517,  1.        ]])

In [ ]:
# x의 각 열 사이의 공분산 구하기, 총 4행 4열의 결괏값이 출력되며 랜덤하게 생성되어 결과는 다를 수 있음
np.cov(x, rowvar=False)

array([[ 0.12966336, -0.01211422, -0.03557149, -0.15501053],
       [-0.01211422,  0.71745894, -0.65856691, -1.0694991 ],
       [-0.03557149, -0.65856691,  0.62134895,  1.04413014],
       [-0.15501053, -1.0694991 ,  1.04413014,  1.8256468 ]])

In [ ]:
# x의 각 행 사이의 공분산 구하기, 총 3행 3열의 결괏값이 출력되며 랜덤하게 생성되어 결과는 다를 수 있음
np.cov(x, rowvar=True)

array([[ 1.65534703, -0.77410372,  0.22475831],
       [-0.77410372,  0.39339777, -0.14000015],
       [ 0.22475831, -0.14000015,  0.17581425]])

In [ ]:
import numpy as np
from scipy import stats
np.random.seed(0)
stats.binom(10, 0.5).rvs(10)   # n=10, p=0.5인 이항 분포에서 rvs 함수로 표본 10개 추출

array([5, 6, 5, 5, 5, 6, 5, 7, 8, 5])

In [ ]:
stats.norm().rvs(10)   # 평균은 0이고, 표준편차가 1인 정규 분포에서 표본 10개 추출

array([ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323,
        0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574])

In [ ]:
stats.uniform().rvs(10)    # 0~1 사이에 정의된 균일 분포에서 표본 10개 추출

array([0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
       0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215])

In [ ]:
stats.chi2(df=2).rvs(10)   # 자유도가 2인 카이제곱 분포에서 표본 10개 추출

array([7.69044368, 3.21047912, 1.23785892, 3.03307195, 0.25174882,
       2.04286377, 0.30945937, 5.7888409 , 1.47565456, 1.07113144])

In [ ]:
x = stats.uniform().rvs(20)   # 균일 분포에서 표본 20개 추출
k2, p = stats.normaltest(x)   # x에 대한 정규성 검정
print(p)   #정규성 검정의 p값을 출력

0.42343504283518196


In [ ]:
import scipy as sp
n = np.array([1, 2, 4, 1, 2, 10])   # 주사위를 20번 던졌을 때 1~6 사이의 눈이 나오는 빈도
sp.stats.chisquare(n)               # 귀무가설 : 각 눈의 빈도는 동일하게 나온다.
# 귀무가설 기각

Power_divergenceResult(statistic=17.799999999999997, pvalue=0.0032077920346052823)

In [ ]:
np.random.seed(0)
x1 = stats.norm(0, 1).rvs(10)   # 평균이 0인 정규 분포에서 표본 10개 추출
x2 = stats.norm(1, 1).rvs(10)   # 평균이 1인 정규 분포에서 표본 10개 추출
np.mean(x1), np.mean(x2)        # 두 랜덤 샘플의 평균 확인

(0.7380231707288347, 1.400646015162435)

In [ ]:
stats.ttest_ind(x1, x2)         # 두 집단의 모평균이 같다는 귀무 가설에 대해 t-검정
# 유의 수준 5%에서 귀무가설 기각

Ttest_indResult(statistic=-1.6868710732328158, pvalue=0.10888146383913824)

In [ ]:
# 어떤 처치의 전후로 통증 크기를 before와 after로 기록하였다. 
# 처치 전의 평균과 처치 후의 평균이 차이가 있는지 쌍체 t 검정으로 확인하기. 
# 숫자가 클수록 통증이 심하며, 통증은 0~100 사이의 값으로 표현

before = [68, 56, 57, 54, 64, 48, 68, 56, 61, 58, 67, 49, 58, 58, 65, 54, 59, 55, 60, 62]
after=[65, 57, 57, 54, 64, 47, 67, 54, 60, 58, 65, 48, 57, 56, 64, 53, 57, 55, 61, 63]
# 귀무 가설: 처치 전후로 통증의 차이가 없다
# 대립 가설: 처치 전후의 통증 차이가 있다

stats.ttest_rel(before, after)
# 유의 수준이 5%라면 현재 p값이 유의 수준보다 작으므로 귀무 가설을 기각

In [ ]:
# 고객 5명에게 광고 전후로 제품에 대한 선호도를 측정하였다. 
# 광고 효과가 있는지 확인하기. 
# 1~10 사이의 값으로 측정, 10: 제품을 매우 선호, 1: 제품을 선호하지 않음

before = [2, 3, 2, 3, 2]
after = [9, 8, 9, 7, 6]
# 귀무 가설: 광고 전후로 선호도 차이가 없다
# 대립 가설: 광고 전후의 선호도 차이가 있다

stats.ttest_rel(before, after)
# 유의 수준이 5%라면 현재 p값이 유의 수준보다 작으므로 귀무 가설을 기각