<a href="https://colab.research.google.com/github/Arachne0/Mathematics_Basics/blob/master/Machine_Learning_for_math_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
(1,2,3) < (4,3,2)      # 두 튜플의 첫 번째 값인 1과 4을 비교

True

In [ ]:
(1,2,3) < (1,3,2)  # 두 튜플의 첫 번째 값이 같으므로 두 번째 값인 2와 3을 비교

True

In [ ]:
('MIT', 'Sun') < ('CIT', 'Sat')  # 첫 번째 값인 MIT와 CIT을 비교

False

In [ ]:
('ABC', 'more' ) < ('ABC', 'most')    # 두 번째 값인 more, most를 비교하는데 세 번째 글자부터 달라서 r과 s를 비교

True

In [ ]:
a = {1, 2, 3}       # 1, 2, 3 값을 갖는 세트 a 생성
b = {3, 4, 5}       # 3, 4, 5 값을 갖는 세트 b 생성

In [ ]:
a.union(b)          # a와 b의 합집합

{1, 2, 3, 4, 5}

In [ ]:
a.intersection(b)   # a와 b의 교집합

{3}

In [ ]:
a - b      # a에서 b를 뺀 차집합

{1, 2}

In [ ]:
a | b      # a와 b의 합집합

{1, 2, 3, 4, 5}

In [ ]:
a & b      # a와 b의 교집합

{3}

In [ ]:
lst = [1, 2, 3, 4]

In [ ]:
lst.append(5)      # 5를 추가
lst.count(5)       # 5의 개수를 출력

2

In [ ]:
lst.insert(0, 7)   # 맨 앞에 7를 추가
lst.pop()          # 끝의 값 1개 반환하고 삭제

5

In [ ]:
lst.reverse()      # 리스트 안에 있는 값을 거꾸로 변환
print(lst)

[5, 4, 3, 2, 1, 7]


In [ ]:
lst.remove(4)      # 4를 제거
print(lst)

[5, 3, 2, 1, 7]


In [ ]:
lst.sort()         # 정렬
print(lst)

[1, 2, 3, 5, 7]


In [ ]:
lst = [18, 21, 32, 48, 56, 64]
lst[0:4]    # 첫 번째~네 번째 값만 가져오기

[18, 21, 32, 48]

In [ ]:
bag = dict()        # 딕셔너리 생성
bag['money'] = 12   # money라는 키 값에 12를 할당
bag['cake'] = 3     # cake라는 키 값에 3을 할당
bag['paper'] = 75   # paper라는 키 값에 75를 할당

In [ ]:
print(bag)

{'money': 12, 'cake': 3, 'paper': 75}


In [ ]:
print(bag['cake'])

3


In [ ]:
print(bag)
{'money': 12, 'cake': 5, 'paper': 75}

{'money': 12, 'cake': 3, 'paper': 75}


{'money': 12, 'cake': 5, 'paper': 75}

In [ ]:
# 리스트
lst = list()    # 리스트 생성
lst.append(11)  # 11을 추가
lst.append(133) # 133도 추가
print(lst)

[11, 133]


In [ ]:
lst[0] = 13 # 첫 번째 값 11을 13으로 수정
print(lst)


[13, 133]


In [ ]:
# 딕셔너리
dic1 = dict()       # 딕셔너리 생성
dic1['age'] = 21    # age 키 값에 21을 할당
dic1['class'] = 182 # class 키 값에 182를 할당
print(dic1)

{'age': 21, 'class': 182}


In [ ]:
dic1['age'] = 23 # age값 21을 23으로 수정
print(dic1)

{'age': 23, 'class': 182}


In [ ]:
'py' 'thon'

'python'

In [ ]:
'py' + 'thon'

'python'

In [ ]:
'py' * 3

'pypypy'

In [ ]:
a = "파이썬"
a[1]

'이'

In [ ]:
a[1:4]

'이썬'

In [ ]:
a[:]       # 처음부터 1칸씩 출력, 3번째 자리에 다른 표현이 없다면 Defalut는 1이다. 

'파이썬'

In [ ]:
a[::2]     # 처음부터 2칸 간격으로 값 출력

'파썬'

In [ ]:
# 실수형에서 문자열로 변환'
num = 3.14
a = str(num)
a

'3.14'

In [ ]:
float(num) + 1.0 

4.140000000000001

In [ ]:
# 문자열에서 정수로 변환
b = int("49")
b

49

In [ ]:
b + 11

60

In [ ]:
# 정수형에서 실수형으로 변환
c = float(23)
c

23.0

In [ ]:
c + 0.9

23.9

In [ ]:
def Times(a, b):
  a = a + 1 # 같은 함수의 내용은 들여쓰기가 같다
  b = b + 1
  return a * b

In [ ]:
# 함수 사용하기
Times(10, 10)

121

In [ ]:
# return이 없으면 None을 반환하는 것을 확인
def setValue(newValue):
  x = newValue
  retval = setValue(10)
  print(retval)

In [ ]:
#리스트 안에 for를 포함하여 실습하기

a = [1, 2, 3, 4]
result = [ ]
for num in a:
  result.append(num * 3)
print(result)  

[3, 6, 9, 12]


In [ ]:
# 리스트 a의 값을 하나씩 num으로 받아 3을 곱해 리스트 result에 넣는다
result = [num * 3 for num in a]

print(result)

[3, 6, 9, 12]


In [ ]:
# 리스트 a의 값 중에서 2로 나눈 나머지가 0인 수만 3을 곱해 리스트 result에 넣는다
result = [num * 3 for num in a if num % 2 == 0]

print(result)

[6, 12]


In [ ]:
#리스트 만들기
clr_names = ['red', 'green', 'gold']
type(clr_names) # 자료 구조의 종류를 알려줌

list

In [ ]:
# 리스트에 값 추가하기
clr_names.append('blue')
clr_names

['red', 'green', 'gold', 'blue']

In [ ]:
# 0부터 시작할 위치를 지정하여 값 추가하기
clr_names.insert(1, 'black')
clr_names

['red', 'black', 'green', 'gold', 'blue']

In [ ]:
t = (1, 2, 3)

a, b = 1, 2
(a, b) = (1, 2)
print(a, b)

1 2


In [ ]:
a, b = b, a
print(a, b)

2 1


In [ ]:
a = set((1, 2, 3))
1 in a

True

In [ ]:
c = tuple(a)
3 in c

True

In [ ]:
d = dict(a = 1, b = 3, c = 5)   # dict로 딕셔너리 생성

In [ ]:
# 세트 안에서 키-값 구조를 이용해 딕셔너리 생성
clr_names = {"apple":"red", "banana":"yellow"}
clr_names

{'apple': 'red', 'banana': 'yellow'}

In [ ]:
clr_names["apple"]

'red'

In [ ]:
clr_names[0]   # 인덱싱을 지원하지 않는다

KeyError: ignored

In [ ]:
# numpy의 array 함수를 쓰기 위해 numpy 패키지를 np라는 이름으로 불러온다
import numpy as np
a = np.array([0, 1, 2, 3, 4, 5])
a.ndim # ndim은 a의 차원 수를 알려준다

(6,)

In [ ]:
# 배열 a의 각 차원에 몇 개의 값이 있는지를 튜플로 반환한다. 값 6개를 갖는 1차원 배열은 다음처럼 표현된다
a.shape

(6,)

In [ ]:
# 배열 a의 값들의 타입을 알려주며, 아래 결과는 정수(integer)임을 의미한다
a.dtype

dtype('int64')

In [ ]:
# 기본 인덱싱
a[[2, 3, 4]]

array([2, 3, 4])

In [ ]:
# 배열을 인덱싱으로 사용할 수 있다
a[np.array([2, 3, 4])]

array([2, 3, 4])

In [ ]:
# 배열 중 원하는 값 출력을 위해 논리 연산하기
a > 4

array([False, False, False, False, False,  True])

In [ ]:
a[a > 4]

array([5])

In [ ]:
x = [0.0, 1, 2, 3, 4]
y = np.array(x)     # 0.0으로 인해 다른 1, 2, 3, 4도 모두 실수형으로 변경되어 배열을 생성
y = np.array([[0.0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])     # 2차원 배열 생성
np.shape(y)   # 행과 열을 확인 

(2, 5)

In [ ]:
y = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]], [[8, 9], [10,11]]])     # 3차원 배열 생성
np.shape(y)   # 3개의 2차원 배열, 각 2차원 배열은 2행 2열임을 순서대로 의미한다

(3, 2, 2)

In [ ]:
# array + for 같이 사용
a = np.array([[1, 2], [3, 4], [5, 6]], float)          # 실수형으로 지정

for x in a:
  print(x)

[1. 2.]
[3. 4.]
[5. 6.]


In [ ]:
# 1차원에서 0~9까지의 정수가 실수형으로 변환한 후 2행 5열 형태로 표현
arr = np.arange(10, dtype = float).reshape((2, 5))
arr[0]       # 1행

array([0., 1., 2., 3., 4.])

In [ ]:
arr[0, 3]    # 1행 3열

3.0

In [ ]:
arr[0][3]    # 1행 3열

3.0

In [ ]:
arr[0, :]    # 1행, 1차원 배열

array([0., 1., 2., 3., 4.])

In [ ]:
arr[:, 0]    # 1열, 1차원 배열

array([0., 5.])

In [ ]:
from pandas import Series, DataFrame
s = Series([0.1, 1.2, 2.3, 3.4, 4.5], index = ['a', 'b', 'c', 'd', 'e'])
s['a']

0.1

In [ ]:
s[0]

0.1

In [ ]:
s[['a', 'c']]

a    0.1
c    2.3
dtype: float64

In [ ]:
s[s > 2]

c    2.3
d    3.4
e    4.5
dtype: float64

In [ ]:
s1 = Series({'a': 0.1, 'b': 1.2, 'c': 2.3})
s2 = Series({'a': 1.0, 'b': 2.0, 'c': 3.0})
s1 + s2

a    1.1
b    3.2
c    5.3
dtype: float64

In [ ]:
s1 = Series(np.arange(10.0, 20.0))
s1.describe()    # 시리즈 s1의 요약 정보 출력

count    10.00000
mean     14.50000
std       3.02765
min      10.00000
25%      12.25000
50%      14.50000
75%      16.75000
max      19.00000
dtype: float64

In [ ]:
summ = s1.describe()
summ['mean']    # 요약 값 중에서 mean 항목 값을 출력


14.5

In [ ]:
s1 = Series(np.arange(1.0, 6), index = ['a', 'a', 'b', 'c', 'd'])
s1.drop('a')    # 시리즈에서 index가 a인 값을 제외

b    3.0
c    4.0
d    5.0
dtype: float64

In [ ]:
# 판다스에서 시리즈와 데이터프레임 함수 불러오기
from pandas import Series, DataFrame

# 딕셔너리로부터 데이터프레임을 생성
raw_data = {'col0': [1, 2, 3, 4],
     'col1': [10, 20, 30, 40],
     'col2': [100, 200, 300, 400]}

data = DataFrame(raw_data)
print(data)

   col0  col1  col2
0     1    10   100
1     2    20   200
2     3    30   300
3     4    40   400


In [ ]:
a = np.array([[1.0, 2], [3, 4]])    # 배열로부터 데이터프레임을 생성
df = DataFrame(a, columns=['dogs', 'cats'], index=['Alice', 'Bob'])
print(df)

       dogs  cats
Alice   1.0   2.0
Bob     3.0   4.0


In [ ]:
import pandas as pd
# 값의 구분자를 \t라는 탭 문자로, 생성할 파일의 인코딩을 utf-8로 지정
df.to_csv('c:/test.csv', sep = '\t', encoding = 'utf-8')
writer = pd.ExcelWriter('c:/test.xlsx')
df.to_excel(writer, 'DataFrame')
writer.save()